# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        # in_memory:
        #     memory: ~

        db_provider:
            entity:
                class: AppBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: login
                check_path: login
                # csrf_token_generator: security.csrf.token_manager
                # csrf_parameter: _csrf_security_token
                # csrf_token_id: _groschaton

            logout:
                path:   /logout
                target: /

            provider: db_provider

            remember_me:
                secret:   '%secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

    access_control:
        # Si user ANONYME : homepage seulement.
        # Si ROLE_USER : accès aux pages de listes post, comment etc. (les liens du menu) et pages show.
        # Sécuriser toutes les routes /new /edit /delete avec ROLE_ADMIN.

        # Admin
        # - { path: ^/(post|author|comment|user)/new, roles: ROLE_ADMIN }
        # - { path: ^/(post|author|comment|user)/\d+/edit, roles: ROLE_ADMIN }
        # - { path: ^/(post|author|comment|user)/\d+, roles: ROLE_ADMIN, methods: [POST, DELETE] }
        # User
        # On peut simplifier l'écriture de (post|author|comment|user) par .* (n'importe que caractère en n'importe quelle quantité)
        # - { path: ^/.*/, roles: ROLE_USER }
        # - { path: ^/.*/\d+, roles: ROLE_USER, methods: [GET] }
        # Anonyme
        # - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
